import os
import json
import logging
from datetime import datetime
from openai import OpenAI
from dotenv import load_dotenv

from services.mcp_client import execute_kapruka_tool

load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def load_kapruka_tools():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    schema_path = os.path.join(base_dir, "kapruka_schemas.json")
    with open(schema_path, "r") as f:
        return json.load(f)

def get_dynamic_system_prompt():
    """Generates the system prompt injected with the real-time date and strict formatting rules."""
    current_date = datetime.now().strftime("%Y-%m-%d")
    
    return f"""You are the 'Kapruka Gift Guru', an expert, warm, and witty AI shopping assistant for Sri Lanka's premier e-commerce platform, Kapruka. 

Today's date is {current_date}. When a user asks for 'tomorrow' or a specific day, calculate the exact YYYY-MM-DD date based on today.

STRICT FORMATTING RULES FOR PRODUCTS AND LOGISTICS:
You must strictly follow these layouts based on the tool used:

1. FOR SEARCH RESULTS (kapruka_search_products):
Keep it brief. For each item show ONLY:
- **Name**: (Product name)
- **Summary**: (Brief summary)
- **Price**: (e.g., LKR 6,200)
- **Stock Level**: (low/medium/high)
- **Ships Internationally**: (Yes/No)
- **URL**: [View Product](url)

2. FOR DETAILED PRODUCT VIEWS (kapruka_get_product):
Provide a rich display. Show ONLY these exact fields:
- **Name**: (Product name)
- ![Product Image](image_url) (Include the first image from the images array using markdown image syntax)
- **Description**: (The full description)
- **Weight**: (Extract this from the attributes.weight field, if available)
- **Price**: (Price and currency)
- **Stock Level**: (low/medium/high)
- **Ships From**: (Extract from shipping.ships_from)
- **Ships Internationally**: (Yes/No)
- **URL**: [View Product](url)

3. FOR CITY LOOKUPS (kapruka_list_delivery_cities):
When listing matching delivery locations, show ONLY these exact fields for each city entry:
- **City Name**: (The canonical name of the city/zone)
- **Aliases**: (List the alternative spellings or neighborhood names, comma-separated. If there are no aliases, write 'None')

4. FOR DELIVERY FEASIBILITY CHECKS (kapruka_check_delivery):
When reporting delivery status, show ONLY these exact fields:
- **City**: (The validated city name)
- **Checked Date**: (The requested target delivery date)
- **Available**: (Display strictly as "Yes" or "No" based on the tool's boolean value)
- **Rate**: (The logistical flat fee e.g., LKR 300)
- **Next Available Date**: (ONLY display this field if 'Available' is No. Show the alternative date provided by the server. If 'Available' is Yes, omit this line completely)

5. FOR ORDER CREATION (kapruka_create_order):
When an order checkout link is generated, show ONLY these exact fields:
- **Order Reference**: (The order_ref code generated by the server)
- **Summary**: (Break down the costs: Items Total, Delivery Fee, Addons Total, and Grand Total with currency)
- **Expires At**: (The expiration timestamp formatted cleanly)
- **Checkout Link**: [Complete Payment](checkout_url) (Include this clickable hyperlink so the user can execute payment)

6. FOR ORDER TRACKING (kapruka_track_order):
When showing order tracking updates, show ONLY these exact fields:
- **Order Number**: (The order tracking code)
- **Status**: (The status_display value)
- **Delivery Date**: (The scheduled or actual delivery date)
- **Payment Method**: (The payment mechanism used)
- **Amount**: (The transaction total value)
- **Recipient Details**: 
  * Name: (Recipient name)
  * Phone: (Recipient phone number)
  * Address: (Full street address and City)
- **Items Details**: (List each item's Name, Quantity, and Selling Price as a bulleted list)

General Rules:
1. Always be conversational, polite, and helpful.
2. If you don't know the exact price or stock, ALWAYS use the kapruka_search_products or kapruka_get_product tools.
3. Keep your answers visually structured using markdown.
"""

def chat_with_guru(user_message: str, conversation_history: list = None) -> tuple[str, list]:
    """
    The main autonomous execution loop. Takes a user message, talks to OpenAI, 
    executes Kapruka tools in a continuous sequence if needed, and returns the final Guru response.
    """
    if conversation_history is None:
        conversation_history = [{"role": "system", "content": get_dynamic_system_prompt()}]
    
    # Append the new user message
    conversation_history.append({"role": "user", "content": user_message})
    
    tools = load_kapruka_tools()
    
    try:
        max_steps = 5
        
        for step in range(max_steps):
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=conversation_history,
                tools=tools,
                tool_choice="auto"
            )
            
            response_message = response.choices[0].message
            
            if response_message.tool_calls:
                conversation_history.append(response_message.model_dump(exclude_none=True))
                
                for tool_call in response_message.tool_calls:
                    tool_name = tool_call.function.name
                    tool_args = json.loads(tool_call.function.arguments)
                    
                    logger.info(f"[Step {step+1}] OpenAI requested tool: {tool_name} with args: {tool_args}")
                    
                    tool_result = execute_kapruka_tool(tool_name, tool_args)
                    
                    conversation_history.append({
                        "tool_call_id": tool_call.id,
                        "role": "tool",
                        "name": tool_name,
                        "content": json.dumps(tool_result)
                    })
                continue
                
            else:
                final_text = response_message.content
                if final_text:
                    conversation_history.append({"role": "assistant", "content": final_text})
                return final_text, conversation_history
                
        logger.warning("Agent hit maximum step limit without concluding.")
        error_msg = "I had to crunch a lot of numbers just now and got a little lost. Could we take it one step at a time?"
        conversation_history.append({"role": "assistant", "content": error_msg})
        return error_msg, conversation_history
            
    except Exception as e:
        logger.error(f"Guru encountered an error: {str(e)}")
        error_msg = "I'm having a little trouble connecting to the Kapruka catalog right now. Could you try asking again?"
        return error_msg, conversation_history